### ISSUE TITLE
Discussão - Modelo de versionamento e organização de pastas das plataformas (Web, iOS, Android)

### ISSUE THREAD

**Issue by luisfernandezbr** [Pagnet/design-tokens#48]
## Motivation

We need to provide a model for structuring the code and versioning that portrays the reality of having 3 types of outputs from a single project. Web, Android and iOS.

## Current scenario

The current model only provides cases for the generation of Web tokens, but we still have the Android and iOS projects to be covered.

In conversation with Elton, we raised some possible points where improvements / adaptations would be necessary, such as CI configurations and versioning rules, so that we can work in a healthy way with the 3 platforms in harmony.

### Versioning

We talked about something that ultimately produces a result like:

``` kotlin
web-v1.0.0
web-v1.1.0
web-v1.2.0

android-v1.0.0
android-v1.1.0
android-v1.2.0

ios-v1.0.0
ios-v1.1.0
ios-v1.2.0
```

The point is that this is only a part, as we have to define the correct version *increment* rule for each case.

To help solve the issue of the *increment* rule, we also thought about maybe changing the project's folder structure, where each platform would end up being independent to do its versioning.

``` kotlin
platforms /
+ - ios
    + - formaters /
    + - package.json
+ - android
    + - formaters /
    + - package.json
+ - web
    + - formaters /
    + - package.json
src /
+ - tokens.yml
package.json
```

To help organize the solution above, Elton even suggested that we take a look at [https://github.com/lerna/lerna](https://github.com/lerna/lerna) to see if it works.

We would like to open this thread to make a decision on how we are going to proceed.

**Comment by eltongarbin** [comment]
@luisfernandezbr What language is that? 🤣
